Deploy website

diff --git a/.github/workflows/add_link_checker.yml b/.github/workflows/add_link_checker.yml
--- a/.github/workflows/add_link_checker.yml
+++ b/.github/workflows/add_link_checker.yml
@@ -26,8 +26,17 @@ jobs:
       env:
         DEPLOYMENT: ${{ inputs.deployment }}
       run: |
-        npm install --global @deptagency/octopus
+        npm install --global @deptagency/octopus@latest
         
         URL=https://$DEPLOYMENT/
         echo "Checking links in $URL"
-        octopus $URL
+
+        # Run octopus and catch errors for better logging
+        set -e
+        {
+          octopus $URL
+        } || {
+          echo "Error occurred while running octopus"
+          echo "Debugging info: URL=$URL, Deployment=$DEPLOYMENT"
+          exit 1
+        }
